config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  post 'user/new', to: 'user#create'
  resources :user
  delete 'session/destroy', to: 'session#destroy' #, as: 'ddd'   路径=ddd_path
  resources :session
  namespace :admin do
    root 'users#index'
    resources :users do
      collection do
        get :search
      end
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: { message: "用户名不能为空" }
  validates :username, uniqueness: { message: "用户名已存在" }
  validates :password, presence: { message: "密码不能为空" }
  validates :password, length: { minimum: 6, message: "密码长度最短为6位" }

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  layout 'admin'

  def index
    @users = User.page(params[:page] || 1).per_page(params[:per_page] || 10).order('id asc').where(['username like ?', "%#{params[:username]}%"])
    total = @users.count
    # 返回json格式数据
    render json: { res: @users, total: total }
  end

  def search
    @users = User.page(params[:page] || 1).per_page(params[:per_page] || 10).order('id asc')
                 .where(['username like ?', "%#{params[:username]}%"])
    total = @users.count
    # render action: :index
    render json: { res: @users, total: total }
  end

  def show
    @user = User.find_by(id: params[:id])
    if @user
      render json: { res: @user }
    else
      render json: { msg: '该用户不存在' }
    end
  end

  def update
    @user = User.find_by(id: params[:id])
    if @user.update(password: params[:password])
      render json: { msg: 'success' }
    else
      render json: { msg: 'failed' }
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #protect_from_forgery with: :exception
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  
  #protect_from_forgery except: :index             ###除了index,controller里的其他action都需要验证
  # protect_from_forgery only: :create              ####只有index需要验证
  def new
  end

  def index
    @users = User.all
  end

  def create
    @user = User.find_by(username: params[:username], password: params[:password])
    if @user
      session[:user_id] = @user.id
      cookies[:user_username] = @user.username
      # flash[:notice] = "登录成功"
      # redirect_to root_path
      render json: { status: 200, user_id: @user.id, user_name: @user.username }
    else
      # flash[:notice] = "用户名或密码不正确"
      # render action: :new   #Rendering 是特别要告诉Controller 中的methods，要哪个view file来显示给用户。We can show Views as we wish!
      render json: { status: 401 }
    end
  end

  def show
    @users = User.all
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "退出成功"
    redirect_to root_path   #另一个控制view内容的方法是redirect, 它跟rendering有点类似，不过它是重新发送一次request到一个different URL. redirect显示了一个不同的view,Redirecting 产生了一个全新的request.
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController

  before_action :auth_user, only: [:index]
  protect_from_forgery except: :index           ###除了index,controller里的其他action都需要验证
  # protect_from_forgery only: :create          ####只有index需要验证
  def index
    # ||逻辑或 如果不传参数进来，默认使用||后面的参数：|| 10   如果不传参数进来，默认使用10
    @users = User.page(params[:page] || 1).per_page(params[:per_page] || 10).order("id desc")
  end

  def new
    @user = User.new
  end

  def create
    # @user = User.new(params.require(:user).permit(:username, :password))
    @user = User.new(username: params[:username], password: params[:password])
    if @user.save
      flash[:notice] = "注册成功，请登录"
      redirect_to new_session_path
    else
      # render :'user/new'
      render action: :new
    end
  end

  private
  def auth_user
    unless session[:user_id]
      flash[:notice] = "请登录"
      redirect_to new_session_path
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/users/_one_user.html.erb
<%#= @users %>
<!--@users对象可以直接传递过来 不需要设置参数 设置参数只是为了传递user-->
<tr>
  <td><%= user.id %></td>
  <td><%= user.username %></td>
</tr>

app/views/admin/users/index.html.erb
<br>
<br>
<br>
<h1>管理后台列表</h1>

<div class="row">
  <div id="col-sm-12">

    <form action="<%= search_admin_users_path %>" method="get">
      用户名：<input type="text" name="username" value="<%= params[:username] %>"/>
      <input type="submit" name="搜索"/>
    </form>

    <table class="table">
      <tr>
        <th>ID</th>
        <th>用户名</th>
        <th></th>
      </tr>
      <%# @users.each do |user| %>
<!--        <tr>-->
<!--          <td><%#= user.id %></td>-->
<!--          <td><%#= user.username %></td>-->
<!--        </tr>-->
      <%# end %>
      <%= render partial: "one_user", collection: @users, as: :user %>
    </table>

    <%= will_paginate @users %>
  </div>

</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Circles</title>
  <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

<header name="top">
  <nav class="navbar navbar-default navbar-fixed-top nav-color" role="navigation" id="nav">
    <div class="container">
      <div class="navbar-header nav-color">
        <button id="nav_collapse" type="button" class="navbar-toggle toggle-btn" data-toggle="collapse" data-target="#bs-navbar-collapse-1"
                aria-controls="bs-navbar-collapse-1">
          <span class="fa fa-bars fa-lg"></span>
        </button>
        <a class="navbar-brand custom-logo-link" href="/">
          Circles后台管理
        </a>
      </div>

      <div class="collapse navbar-collapse nav-submenu-color collapse" id="bs-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right custom">
          <li>
            <a href="/">Home</a>
          </li>
          <li>
            <a href="<%= admin_users_path %>">后台管理-用户列表</a>
          </li>

          <% if session[:user_id] %>
            <li>
              <%= link_to "#{cookies[:user_username]} 退出", session_destroy_path(@user), method: :delete %>
              <%#= link_to "#{@user.username} 退出", session_destroy_path(@user), method: :delete %>
            </li>
          <% else %>
            <li>
              <%= link_to "登录", new_session_path %>
            </li>
            <li>
              <%= link_to "注册", new_user_path %>
            </li>
          <% end -%>
        </ul>

      </div>
    </div>
  </nav>
</header>

<div class="container body-offset">
  <% if flash[:notice] %>
    <br>
    <br>
    <br>
    <div class="alert alert-info"><%= flash[:notice] %></div>
  <% end -%>

  <%= yield %>

</div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Circles</title>
  <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

<header name="top">
  <nav class="navbar navbar-default navbar-fixed-top nav-color" role="navigation" id="nav">
    <div class="container">
      <div class="navbar-header nav-color">
        <button id="nav_collapse" type="button" class="navbar-toggle toggle-btn" data-toggle="collapse" data-target="#bs-navbar-collapse-1"
                aria-controls="bs-navbar-collapse-1">
          <span class="fa fa-bars fa-lg"></span>
        </button>
        <a class="navbar-brand custom-logo-link" href="/">
          Circles
        </a>
      </div>

      <div class="collapse navbar-collapse nav-submenu-color collapse" id="bs-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right custom">
          <li>
            <a href="/">Home</a>
          </li>
          <li>
            <a href="<%= user_index_path %>">用户列表</a>
          </li>

          <% if session[:user_id] %>
            <li>
              <%= link_to "#{cookies[:user_username]} 退出", session_destroy_path(@user), method: :delete %>
              <%#= link_to "#{@user.username} 退出", session_destroy_path(@user), method: :delete %>
            </li>
          <% else %>
            <li>
              <%= link_to "登录", new_session_path %>
            </li>
          <% end -%>
        </ul>

      </div>
    </div>
  </nav>
</header>

<div class="container body-offset">
  <% if flash[:notice] %>
    <br>
    <br>
    <br>
    <div class="alert alert-info"><%= flash[:notice] %></div>
  <% end -%>

  <%= yield %>

</div>
</body>
</html>

app/views/session/new.html.erb
<br>
<br>
<br>
<h1>用户登录</h1>

<div class="row">
  <div class="col-sm-4">
    <%= form_tag session_index_path, method: "post" do %>
      <div class="form-group">
        <input type="text" name="username" placeholder="用户名..." class="form-control" id="form_username" title="用户名6-12个字符">
      </div>
      <div class="form-group">
        <input type="password" name="password" placeholder="密码..." class="form-control" id="form_password">
      </div>
      <input type="submit" class="btn btn-primary" value="登录">
      <%= link_to "注册", new_user_path %>
    <% end %>
  </div>
  <div class="col-sm-8">
  </div>

</div>

app/views/user/index.html.erb
<br>
<br>
<br>
<h1>用户列表</h1>

<div class="row">
  <div id="col-sm-12">
    <table class="table">
      <tr>
        <th>ID</th>
        <th>用户名</th>
        <th></th>
      </tr>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.id %></td>
          <td><%= user.username %></td>
        </tr>
      <% end %>
    </table>

    <%= will_paginate @users %>
  </div>

</div>

app/views/user/new.html.erb
<br>
<br>
<br>
<h1>用户注册</h1>

<div class="row">
  <div class="col-sm-5">
    <%#= form_for @user, url: user_path, method: :post do |f| %>
    <%= form_for user_index_path, method: "post" do %>
      <div class="form-group">
        <ul class="list-unstyled">
          <% @user.errors.messages.values.flatten.each do |error| %>
            <li><i class="fa fa-exclamation-circle"></i> <%= error %></li>
          <% end %>
        </ul>
      </div>

      <div class="form-group">
        <%#= f.text_field :username, class: "form-control", placeholder: "用户名" %>
        <input type="text" name="username" placeholder="用户名..." class="form-control" id="form_username" title="用户名6-12个字符">

      </div>

      <div class="form-group">
        <%#= f.password_field :password, class: "form-control", placeholder: "密码" %>
        <input type="password" name="password" placeholder="密码..." class="form-control" id="form_password">

      </div>

      <%#= f.submit "注册", class: "btn btn-primary" %>
      <input type="submit" class="btn btn-primary" value="注册">
      <%= link_to "登录", new_session_path %>
    <% end %>
  </div>
</div>

app/views/welcome/index.html.erb
<br>
<br>
<br>
<h1>This is a circles homepage</h1>

<div class="alert alert-success">
  mm
</div>